# Generated by Django 5.2.17 on 2026-08-26 14:38

import apps.projects.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product name — usually not translated.', max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('tagline_en', models.CharField(help_text='One line. What it does, for whom.', max_length=220)),
                ('tagline_uz', models.CharField(blank=True, max_length=220)),
                ('tagline_de', models.CharField(blank=True, max_length=220)),
                ('tagline_ru', models.CharField(blank=True, max_length=220)),
                ('role_en', models.CharField(blank=True, help_text='e.g. Backend + Computer Vision', max_length=140)),
                ('role_uz', models.CharField(blank=True, max_length=140)),
                ('role_de', models.CharField(blank=True, max_length=140)),
                ('role_ru', models.CharField(blank=True, max_length=140)),
                ('summary_en', models.TextField(blank=True, help_text='2–4 sentences shown in the list. Markdown.')),
                ('summary_uz', models.TextField(blank=True)),
                ('summary_de', models.TextField(blank=True)),
                ('summary_ru', models.TextField(blank=True)),
                ('context_en', models.TextField(blank=True, help_text='Who it was for, team size, timeframe. Markdown.')),
                ('context_uz', models.TextField(blank=True)),
                ('context_de', models.TextField(blank=True)),
                ('context_ru', models.TextField(blank=True)),
                ('organisation', models.CharField(blank=True, help_text='Company or university.', max_length=140)),
                ('year_started', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_finished', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('production', 'In production'), ('research', 'Research'), ('wip', 'In progress'), ('archived', 'Archived')], default='production', max_length=12)),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('is_confidential', models.BooleanField(default=False, help_text="Show a 'source code is private' note instead of repo links.")),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = higher on the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-year_started', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('backend', 'Backend'), ('ai', 'AI / Computer Vision'), ('data', 'Data'), ('frontend', 'Frontend'), ('infra', 'Infrastructure'), ('tool', 'Tooling')], default='tool', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(help_text='e.g. Manual data entry', max_length=90)),
                ('label_uz', models.CharField(blank=True, max_length=90)),
                ('label_de', models.CharField(blank=True, max_length=90)),
                ('label_ru', models.CharField(blank=True, max_length=90)),
                ('value_before', models.CharField(blank=True, help_text='e.g. 40 min/day', max_length=40)),
                ('value_after', models.CharField(help_text='e.g. 4 min/day', max_length=40)),
                ('note_en', models.CharField(blank=True, max_length=140)),
                ('note_uz', models.CharField(blank=True, max_length=140)),
                ('note_de', models.CharField(blank=True, max_length=140)),
                ('note_ru', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('problem', 'Problem'), ('constraints', 'Constraints'), ('decision', 'Decisions & trade-offs'), ('architecture', 'Architecture'), ('result', 'Outcome'), ('retro', "What I'd do differently"), ('custom', 'Custom section')], default='problem', max_length=14)),
                ('heading_en', models.CharField(blank=True, help_text='Leave empty to use the section type name.', max_length=160)),
                ('heading_uz', models.CharField(blank=True, max_length=160)),
                ('heading_de', models.CharField(blank=True, max_length=160)),
                ('heading_ru', models.CharField(blank=True, max_length=160)),
                ('body_en', models.TextField(help_text='Markdown: **bold**, lists, `code`.')),
                ('body_uz', models.TextField(blank=True)),
                ('body_de', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Case study section',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.projects.models.project_image_path)),
                ('alt_text_en', models.CharField(help_text='Required. Describe the image for screen readers.', max_length=200)),
                ('alt_text_uz', models.CharField(blank=True, max_length=200)),
                ('alt_text_de', models.CharField(blank=True, max_length=200)),
                ('alt_text_ru', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=220)),
                ('caption_uz', models.CharField(blank=True, max_length=220)),
                ('caption_de', models.CharField(blank=True, max_length=220)),
                ('caption_ru', models.CharField(blank=True, max_length=220)),
                ('is_primary', models.BooleanField(default=False, help_text='The large image. Only one per project.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Image',
                'ordering': ['-is_primary', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology'),
        ),
    ]
