# Generated by Django 5.2.17 on 2026-08-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=120)),
                ('title_uz', models.CharField(blank=True, max_length=120)),
                ('title_de', models.CharField(blank=True, max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('body_en', models.TextField()),
                ('body_uz', models.TextField(blank=True)),
                ('body_de', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Principle',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Nizomiddin Xalilov', max_length=120)),
                ('job_title', models.CharField(default='Backend & Computer Vision Engineer', help_text='Shown under the name. Keep it short.', max_length=140)),
                ('location', models.CharField(blank=True, default='Tashkent, Uzbekistan', max_length=120)),
                ('headline_en', models.CharField(blank=True, max_length=220)),
                ('headline_uz', models.CharField(blank=True, max_length=220)),
                ('headline_de', models.CharField(blank=True, max_length=220)),
                ('headline_ru', models.CharField(blank=True, max_length=220)),
                ('intro_en', models.TextField(blank=True, help_text='1–2 sentences under the headline.')),
                ('intro_uz', models.TextField(blank=True)),
                ('intro_de', models.TextField(blank=True)),
                ('intro_ru', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True, help_text='About page. Markdown supported.')),
                ('about_uz', models.TextField(blank=True)),
                ('about_de', models.TextField(blank=True)),
                ('about_ru', models.TextField(blank=True)),
                ('work_philosophy_en', models.TextField(blank=True, help_text="'How I work' intro. Markdown.")),
                ('work_philosophy_uz', models.TextField(blank=True)),
                ('work_philosophy_de', models.TextField(blank=True)),
                ('work_philosophy_ru', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('open', 'Open to opportunities'), ('selective', 'Open to selected projects'), ('busy', 'Not available right now')], default='open', max_length=12)),
                ('availability_note_en', models.CharField(blank=True, max_length=180)),
                ('availability_note_uz', models.CharField(blank=True, max_length=180)),
                ('availability_note_de', models.CharField(blank=True, max_length=180)),
                ('availability_note_ru', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('avatar', models.ImageField(blank=True, help_text='Square photo, at least 600×600.', upload_to='site/')),
                ('og_image', models.ImageField(blank=True, help_text='1200×630 social preview.', upload_to='site/')),
                ('cv_file', models.FileField(blank=True, help_text='Optional. If empty, the /cv/ page is used for printing to PDF.', upload_to='site/')),
                ('github_username', models.CharField(blank=True, help_text='For live GitHub stats.', max_length=60)),
                ('meta_description_en', models.CharField(blank=True, max_length=200)),
                ('meta_description_uz', models.CharField(blank=True, max_length=200)),
                ('meta_description_de', models.CharField(blank=True, max_length=200)),
                ('meta_description_ru', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(help_text='Full URL, or mailto:/tel: link.', max_length=300)),
                ('icon', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('mail', 'Email'), ('x', 'X / Twitter'), ('globe', 'Website'), ('phone', 'Phone'), ('kaggle', 'Kaggle')], default='globe', max_length=20)),
                ('show_in_header', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social link',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Page view',
                'ordering': ['-date', '-count'],
                'unique_together': {('path', 'date')},
            },
        ),
    ]
