# Generated by Django 5.2.17 on 2026-09-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='avatar_crop',
            field=models.CharField(blank=True, help_text='Set by the cropper: x,y,width,height in pixels of the original.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='avatar_display',
            field=models.ImageField(blank=True, editable=False, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Portrait photo, ideally 1200 px tall or more. Crop it below.', upload_to='site/'),
        ),
    ]
