# Generated by Django 5.2.17 on 2026-09-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portrait_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visitor', models.CharField(max_length=32)),
                ('device', models.CharField(blank=True, max_length=10)),
                ('referrer', models.CharField(blank=True, max_length=120)),
                ('first_path', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Visitor',
                'unique_together': {('date', 'visitor')},
            },
        ),
    ]
