# Generated by Django 5.2.17 on 2026-08-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=180)),
                ('title_uz', models.CharField(blank=True, max_length=180)),
                ('title_de', models.CharField(blank=True, max_length=180)),
                ('title_ru', models.CharField(blank=True, max_length=180)),
                ('description_en', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('issuer', models.CharField(blank=True, max_length=180)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Award / recognition',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=180)),
                ('institution_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('degree_en', models.CharField(max_length=140)),
                ('degree_uz', models.CharField(blank=True, max_length=140)),
                ('degree_de', models.CharField(blank=True, max_length=140)),
                ('degree_ru', models.CharField(blank=True, max_length=140)),
                ('field_of_study_en', models.CharField(blank=True, max_length=160)),
                ('field_of_study_uz', models.CharField(blank=True, max_length=160)),
                ('field_of_study_de', models.CharField(blank=True, max_length=160)),
                ('field_of_study_ru', models.CharField(blank=True, max_length=160)),
                ('note_en', models.TextField(blank=True)),
                ('note_uz', models.TextField(blank=True)),
                ('note_de', models.TextField(blank=True)),
                ('note_ru', models.TextField(blank=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, help_text='e.g. GPA 4.5 / 5.0', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=140)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('role_en', models.CharField(max_length=160)),
                ('role_uz', models.CharField(blank=True, max_length=160)),
                ('role_de', models.CharField(blank=True, max_length=160)),
                ('role_ru', models.CharField(blank=True, max_length=160)),
                ('employment_type_en', models.CharField(blank=True, help_text='Full-time, Contract…', max_length=60)),
                ('employment_type_uz', models.CharField(blank=True, max_length=60)),
                ('employment_type_de', models.CharField(blank=True, max_length=60)),
                ('employment_type_ru', models.CharField(blank=True, max_length=60)),
                ('summary_en', models.TextField(blank=True, help_text='Markdown. 1–3 sentences.')),
                ('summary_uz', models.TextField(blank=True)),
                ('summary_de', models.TextField(blank=True)),
                ('summary_ru', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if this is your current job.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=60)),
                ('name_uz', models.CharField(blank=True, max_length=60)),
                ('name_de', models.CharField(blank=True, max_length=60)),
                ('name_ru', models.CharField(blank=True, max_length=60)),
                ('level_en', models.CharField(help_text='e.g. Native, IELTS 6.0 (B2)', max_length=80)),
                ('level_uz', models.CharField(blank=True, max_length=80)),
                ('level_de', models.CharField(blank=True, max_length=80)),
                ('level_ru', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('note_en', models.CharField(blank=True, max_length=200)),
                ('note_uz', models.CharField(blank=True, max_length=200)),
                ('note_de', models.CharField(blank=True, max_length=200)),
                ('note_ru', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill group',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=300)),
                ('text_uz', models.CharField(blank=True, max_length=300)),
                ('text_de', models.CharField(blank=True, max_length=300)),
                ('text_ru', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='resume.experience')),
            ],
            options={
                'verbose_name': 'Bullet point',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('depth', models.CharField(choices=[('core', 'Core — daily driver'), ('strong', 'Strong — used in production'), ('working', 'Working knowledge')], default='strong', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
