# Generated by Django 5.2.17 on 2026-09-26 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="e.g. IELTS Academic 7.0, Bachelor's diploma",
                        max_length=180,
                    ),
                ),
                ("title_uz", models.CharField(blank=True, max_length=180)),
                ("title_ru", models.CharField(blank=True, max_length=180)),
                (
                    "file",
                    models.FileField(
                        help_text="PDF or image (JPG, PNG, WEBP).",
                        upload_to="certificates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["order", "id"],
            },
        ),
    ]
