# Generated by Django 5.2.17 on 2026-09-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("params", models.JSONField(default=dict)),
                ("summary", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Waiting for confirmation"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="proposed",
                        max_length=10,
                    ),
                ),
                ("channel", models.CharField(default="site", max_length=10)),
                ("tg_msgs", models.JSONField(blank=True, default=list)),
                ("result", models.CharField(blank=True, max_length=300)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AI action",
                "verbose_name_plural": "AI actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("lang", models.CharField(default="uz", max_length=5)),
                ("mode", models.CharField(default="local", max_length=6)),
                ("state", models.CharField(default="idle", max_length=6)),
                ("run", models.CharField(blank=True, max_length=36)),
                ("history", models.JSONField(blank=True, default=list)),
                ("busy_since", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram chat",
                "verbose_name_plural": "Telegram chats",
            },
        ),
        migrations.CreateModel(
            name="AiKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="One fact per row, in any language."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI fact",
                "verbose_name_plural": "AI facts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("telegram", "Telegram"),
                            ("system", "System"),
                        ],
                        default="site",
                        max_length=10,
                    ),
                ),
                ("role", models.CharField(default="guest", max_length=6)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ask", "Question"),
                            ("voice", "Voice"),
                            ("file", "Image / PDF"),
                            ("digest", "Digest"),
                            ("action", "Action"),
                        ],
                        default="ask",
                        max_length=8,
                    ),
                ),
                ("lang", models.CharField(blank=True, max_length=5)),
                ("mode", models.CharField(blank=True, max_length=6)),
                ("question", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=60)),
                ("steps", models.PositiveSmallIntegerField(default=0)),
                ("tools_used", models.CharField(blank=True, max_length=200)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("ms", models.PositiveIntegerField(default=0)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "unanswered",
                    models.BooleanField(
                        default=False,
                        help_text="The assistant had no facts for this question.",
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=32)),
                ("session", models.CharField(blank=True, db_index=True, max_length=40)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "AI request",
                "verbose_name_plural": "AI requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "contact",
                    models.CharField(
                        help_text="Email, Telegram username or phone.", max_length=200
                    ),
                ),
                (
                    "need",
                    models.TextField(
                        help_text="What they want to build, in their words."
                    ),
                ),
                ("timeline", models.CharField(blank=True, max_length=120)),
                ("budget", models.CharField(blank=True, max_length=120)),
                ("lang", models.CharField(blank=True, max_length=5)),
                ("page", models.CharField(blank=True, max_length=300)),
                ("ip_hash", models.CharField(blank=True, max_length=32)),
                ("session", models.CharField(blank=True, max_length=40)),
                ("transcript", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("due_at", models.DateTimeField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["due_at"],
            },
        ),
    ]
