# Generated by Django 5.2.17 on 2026-09-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_ai_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichat",
            name="digest_on",
            field=models.BooleanField(
                default=True, help_text="Send the 08:30 / 18:00 report here."
            ),
        ),
    ]
