# Generated by Django 5.2.17 on 2026-09-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_chat_digest_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichat",
            name="auto_confirm",
            field=models.BooleanField(
                default=True,
                help_text="Apply changes at once (with an undo button) instead of asking to confirm.",
            ),
        ),
        migrations.AlterField(
            model_name="aiaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Waiting for confirmation"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                    ("undone", "Undone"),
                ],
                default="proposed",
                max_length=10,
            ),
        ),
    ]
